name: .NET - Build

on:
  push:
    branches: [ "main" ]
  release:
    types: [ published ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./src/fake-web-api
      run: dotnet restore
    - name: Build
      working-directory: ./src/fake-web-api
      run: dotnet build --no-restore -o "./out"
    - name: Generate SBOM
      working-directory: ./src/fake-web-api
      run: |
        curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod +x $RUNNER_TEMP/sbom-tool
        $RUNNER_TEMP/sbom-tool generate -b ./out -bc . -pn ${{ github.event.repository.name }} -pv ${{ github.run_number }} -nsb https://sbom.medium.com.au -V Verbose
        ls ./out/_manifest/spdx_2.2/
      shell: bash
    - name: upload SBOM artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sbom-artifacts
        path: ./src/fake-web-api/out/_manifest/spdx_2.2/*
    - name: update to release asset
      if: ${{ github.event.release != null }}
      uses: echapmanFromBunnings/upload-release-assets@1.1
      with:          
        releaseTag: ${{ github.event.release.tag_name }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        files: |
          ./src/fake-web-api/out/_manifest/spdx_2.2/*
    - name: Test
      working-directory: ./src/fake-web-api
      run: dotnet test --no-build --verbosity normal
